### ISSUE TITLE
latest 1.19.2 presence footsteps crashes with latest 1.19.2 immersive portals.

### ISSUE THREAD

**Issue by arisugawaa** [PaintNinja/Presence-Footsteps-Forge#12]
exit code 1.
on recommended forge 1.19.2 - 43.2.0

**Comment by PaintNinja** [comment]
Exit code 1 literally only means "something crashed". Please may you upload the latest.log or debug.log to https://mclo.gs so I can help?

**Comment by arisugawaa** [comment]
oh i see, ive lost the log but will definitely update when if it happens again.
