### ISSUE TITLE
F3 Doesn't show coordinates when presence footsteps is installed

### ISSUE THREAD

**Issue by InteJason** [PaintNinja/Presence-Footsteps-Forge#2]
Forge 40.1.20
1.18.2-1.5.0-beta1

Tested with and without presence footsteps mod, this issue only occur with it installed

**Comment by D-Bigboy-302** [comment]
I am also having this issue. Took me a while to figure out which mod was causing it.

**Comment by Leonime** [comment]
I'm having the same problem, I kind of solve it by installed the BetterFPS, it returns some of the output but, there's still some info missing.

**Comment by Lozf** [comment]
Same, hitting f3 does nothing with this mod installed, except change the crosshairs.

**Comment by TaggedDev** [comment]
Same for me. Pressing F3 doesn't show up Debug menu

**Comment by ChloeDawn** [comment]
This is caused by the same error reported in https://github.com/PaintNinja/Presence-Footsteps-Forge/issues/3

**Comment by PaintNinja** [comment]
Thanks for your report. I've fixed this in 1.18.2-1.5.0-beta2.

https://www.curseforge.com/minecraft/mc-mods/presence-footsteps-forge
