### ISSUE TITLE
Error rendering overlay 'Text Columns' loop

### ISSUE THREAD

**Issue by MattB70** [PaintNinja/Presence-Footsteps-Forge#3]
When loading resources (trigger easily be changing a resource pack), Presence Footsteps can loop forever on this error:

`Cannot invoke "eu.ha3.presencefootsteps.PFDebugHud.render(net.minecraft.world.phys.HitResult, net.minecraft.world.phys.HitResult, java.util.List)" because the return value of "eu.ha3.presencefootsteps.PresenceFootsteps.getDebugHud()" is null`

Full log (very long as it loops until crashing from running out of memory):
https://gist.github.com/MattB70/071842981ff0f582355bfface6b5d4d0

It looks like getDebugHud() is missing, hidden, or unfinished. Adding a null checker will be an easy patch.

**Comment by PaintNinja** [comment]
Thanks for your report. I've fixed this in 1.18.2-1.5.0-beta2 by removing the mixin referencing the debug hud entirely rather than adding overhead with a null check.

https://www.curseforge.com/minecraft/mc-mods/presence-footsteps-forge
