### ISSUE TITLE
Forge Version Mismatch (1.20.1)

### ISSUE THREAD

**Issue by Processhf** [PaintNinja/Presence-Footsteps-Forge#32]
The 1.20.1 version of the mod is requesting version 47.2.19 of Forge, which does not exist for 1.20.1 Minecraft. The correct version would be 47.2.0
![image](https://github.com/PaintNinja/Presence-Footsteps-Forge/assets/17095896/0e188d09-c58c-472f-8f66-8b476cd390c0)

**Comment by PaintNinja** [comment]
https://files.minecraftforge.net/net/minecraftforge/forge/index_1.20.1.html
