### ISSUE TITLE
Crash on modded.

### ISSUE THREAD

**Issue by Atlantispy** [PaintNinja/Presence-Footsteps-Forge#6]
[crash-2022-08-14_21.56.28-client.txt](https://github.com/PaintNinja/Presence-Footsteps-Forge/files/9334138/crash-2022-08-14_21.56.28-client.txt)

Fixes when I disable presence, related to a shulker

**Comment by PaintNinja** [comment]
Does this still happen on the 1.19.2 version of the Forge port?

**Comment by PaintNinja** [comment]
Closing as unable to reproduce and no response. If the issue persists on a newer version of the mod please let me know

**Comment by AlternateYT** [comment]
This happens for me on 1.19.2, saying that it's missing dependencies in the log file but doesn't list the actual needed dependencies.

**Comment by PaintNinja** [comment]
@AlternateYT Please provide your debug.log found in the logs folder and I'll investigate
