### ISSUE TITLE
[1.19.2] Stepping on water making stone sounds.

### ISSUE THREAD

**Issue by murao-kun** [PaintNinja/Presence-Footsteps-Forge#7]
If you are on the edge of the block with water, the mod making stone stepping sounds.

**Comment by PaintNinja** [comment]
Unable to reproduce. Please try the latest version of the mod and file a new issue (mentioning the version you're using) if the problem persists.
https://www.curseforge.com/minecraft/mc-mods/presence-footsteps-forge/files
