### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by Looodon** [PaintNinja/Presence-Footsteps-Forge#9]
Hey,
My game crashed and I couldn't get into my world anymore cuz it kept crashing until I removed the mod. Any thoughts as to why?

Crash Log:
https://paste.gg/p/anonymous/e7d63fede6f740efbc3d4d9d1e170e90

**Comment by twilight-sparkle-irl** [comment]
Agreed, having same issue. https://crashy.net/w4RZOYGO9ocmAFgvxx1y

**Comment by PaintNinja** [comment]
Thanks for your report and sorry for the delay, it should be fixed now.
https://www.curseforge.com/minecraft/mc-mods/presence-footsteps-forge/files
